<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserParent($id)
    {

        $qb=$this->createQueryBuilder('q');
        $qb->select('u')
            ->from('UserBundle:User', 'u')
            ->where('u.parent = :uid')
            ->orderBy('u.username','ASC')
            ->setParameter('uid', $id);

        return $qb;
    }
}
